# Wire up travis
language: python
sudo: false

python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get install openslide-tools

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt

# command to run tests
script:
  - pytest --cov=src.histolab

after_success:
  - coveralls