# Wire up travis

language: python            # this works for Linux but is an error on macOS or Windows
env:
  - CAN_FAIL=false
jobs:
  include:
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7          # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.8 on Xenial Linux"
      python: 3.8          # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.6.5 on macOS"
      os: osx
      osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - brew update-reset
        - source ~/.bash_profile
        - brew update
        - brew install openslide
        - echo 'export PATH="/usr/local/Frameworks/Python.framework/Versions/Current/bin:$PATH"' >> /Users/travis/.bash_profile
        - echo $PATH
      env: CAN_FAIL=true
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - brew install openslide
        - echo 'export PATH="/usr/local/Frameworks/Python.framework/Versions/Current/bin:$PATH"' >> /Users/travis/.bash_profile
        - echo $PATH
    - name: "Python 3.8.3 on macOS"
      os: osx
      osx_image: xcode12u
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - brew install openslide
        - echo 'export PATH="/usr/local/Frameworks/Python.framework/Versions/Current/bin:$PATH"' >> /Users/travis/.bash_profile
        - echo $PATH
    - name: "Python 3.6.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install --upgrade pip
        - wget https://github.com/openslide/openslide-winbuild/releases/download/v20171122/openslide-win64-20171122.zip -P /c/downloads
        - 7z e /c/downloads/openslide-win64-20171122.zip -aoa
        - export "PATH=/c/Python36:/c/Python36/Scripts:/c/downloads/openslide-win64-20171122/bin:$PATH"
    - name: "Python 3.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7
        - python -m pip install --upgrade pip
        - wget https://github.com/openslide/openslide-winbuild/releases/download/v20171122/openslide-win64-20171122.zip -P /c/downloads
        - 7z e /c/downloads/openslide-win64-20171122.zip -aoa
        - export "PATH=/c/Python37:/c/Python37/Scripts:/c/downloads/openslide-win64-20171122/bin:$PATH"
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - wget https://github.com/openslide/openslide-winbuild/releases/download/v20171122/openslide-win64-20171122.zip -P /c/downloads
        - 7z e /c/downloads/openslide-win64-20171122.zip -aoa
        - export "PATH=/c/Python38:/c/Python38/Scripts:/c/downloads/openslide-win64-20171122/bin:$PATH"
      env: CAN_FAIL=true
  allow_failures:
    - env: CAN_FAIL=true
  fast_finish: true

# command to install dependencies
install:
  - pip3 install -e .[testing]
  - pip3 install flake8
  - pip3 install pooch

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0
  - sleep 3 # give xvfb some time to start

# command to run tests
script:
  - flake8 .
  - pytest --ignore=tests/benchmarks --cov=histolab # benchmarks must be in a separate pipeline - not on travis

after_success:
  - coveralls

notifications:
  slack: mpba:fBrjUWlUSa3XKeCA8zFsTFu2

addons:
  apt:
    packages: openslide-tools