# Wire up travis
language: python

language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7          # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.6.5 on macOS"
      os: osx
      osx_image: xcode9.4  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - brew update
        - brew install openslide
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - brew install openslide
    - name: "Python 3.6 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

# command to install dependencies
install:
  - pip3 install -e .[testing]
  - pip3 install flake8

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0
  - sleep 3 # give xvfb some time to start

# command to run tests
script:
  - flake8 .
  - pytest --cov=histolab

after_success:
  - coveralls

notifications:
  slack: mpba:fBrjUWlUSa3XKeCA8zFsTFu2

addons:
  apt:
    packages: openslide-tools